<?php


namespace Axharus\ArtHandler;


use App\Exceptions\Handler;
use \Illuminate\Contracts\Debug\ExceptionHandler;
use Throwable;

class ArtHandler extends Handler implements ExceptionHandler {

    public function report($e) {

        try {
            $message = "Status code => ".$e->getStatusCode()."\n";
            $message .= "Info => ".$e->getMessage()."\n";
            $message .= "Trace => ".$e->getTraceAsString();
            $sender  = new ArtHandlerSender([
                "type"          => "php",
                "error_content" => $message,
                "screen_size"   => "",
                "status_code"      => $e->getStatusCode()
            ]);
            $sender->send();
        } catch (\Exception $e) {
            var_dump('ArtHandlerFail');
        }

        return parent::report($e);
    }

    public function render($request, Throwable $e) {
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
